name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with Buildozer
        run: |
          buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: kto_podaet-release
          path: bin/*.apk
