name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with Buildozer
        run: |
          buildozer android release

  
